name: mfp-client
dependencies:
  polymer: ^1.0.0-rc.2
  web_components: ^0.12.0
  reflectable: ^0.3.0
transformers:
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.html